# Generated by Django 5.1.1 on 2024-10-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('film', 'Film'), ('dizi', 'Dizi'), ('kitap', 'Kitap'), ('anime', 'Anime')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('macera', 'Macera'), ('korku', 'Korku'), ('komedi', 'Komedi'), ('dram', 'Dram'), ('fantastik', 'Fantastik'), ('gerilim', 'Gerilim'), ('romantik', 'Romantik'), ('aksiyon', 'Aksiyon'), ('bilimkurgu', 'Bilim Kurgu'), ('gizem', 'Gizem'), ('belgesel', 'Belgesel'), ('biyografi', 'Biyografi'), ('suç', 'Suç'), ('savaş', 'Savaş'), ('tarih', 'Tarih'), ('müzikal', 'Müzikal'), ('psikolojik', 'Psikolojik'), ('spor', 'Spor'), ('western', 'Western'), ('animasyon', 'Animasyon'), ('çocuk', 'Çocuk'), ('kısa', 'Kısa Film'), ('sanat', 'Sanat'), ('distopya', 'Distopya')], max_length=50, unique=True)),
            ],
        ),
    ]
